version: '3.8'

services:
  spark:
    build: ./spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ./data:/data
      
  spark-worker:
    build: ./spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./data:/data

  jupyter:
    build: ./jupyter/
    environment:
      - S3_ENDPOINT=http://minio:9001
      - S3_BUCKET= bronze
      - S3_ACCESS_KEY= ${MINIO_ACCESS_KEY}
      - S3_SECRET_KEY= ${MINIO_SECRET_KEY}
    ports: 
      - 8888:8888
    volumes:
      #- ./data:/data
      - ./jupyter/notebooks/:/notebooks/

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}               # usuário root para o MinIO
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}       # senha root para o MinIO
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
      - ./minio/include:/include                        # Volume para dados a serem copiados
      - ./minio/bucket-init.sh:/bucket-init.sh          # Script para criar buckets e fazer upload
      - ./minio/data:/data                              # Pasta persistente para dados do MinIO
      - ./minio/minio-client:/root/.mc                  # Configuração persistente do MinIO Client
    entrypoint: /bin/sh -c "/bucket-init.sh && /usr/bin/docker-entrypoint.sh minio server /data --console-address ':9001'"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - lakehouse-network

volumes:
  minio_data:

networks:
  lakehouse-network:
    driver: bridge
